services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install python-telegram-bot==22.1
      pip install -r requirements.txt || true
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8054080132:AAEW20FIMr-Fpr6y12xh0kYFvXB_iTTjJe4
      - key: WEBHOOK_URL
        value: https://telegram-bot-anxietyxrl.onrender.com
      - key: PORT
        value: 10000
