services:
  - type: worker
    name: postbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_real_token_here
      - key: PORT
        value: "8000"  # ← добавлен только если Render требует
