services:
  - type: web
    name: telegram-postbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python postbot.py
    autoDeplay: true 
    envVars:
      - key: BOT_TOKEN
        value: 8054080132:AAEW20FIMr-Fpr6y12xh0kYFvXB_iTTjJe4
      - key: WEBHOOK_URL
        value: https://telegram-bot-anxietyxrl.onrender.com/webhook
