services:
  - type: web
    name: bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_token_here
      - key: WEBHOOK_HOST
        value: https://your-render-url.onrender.com
      - key: WEBHOOK_PORT
        value: 10000
